In [1]:
import pandas as pd
import numpy as np
import inspect
import os
import redis
import json
redis_conn = redis.Redis(host='localhost',port=6379,db=1)

In [2]:
file_path = inspect.getfile(inspect.currentframe())
file_direction = os.path.dirname(os.path.abspath(file_path))
offertagging = os.path.join(file_direction, 'MJ_OFFER.xlsx')

In [3]:
offertagging = pd.read_excel(offertagging)

In [4]:
offertagging = offertagging[['LABEL_ID','OFFER_ID']].drop_duplicates().reset_index(drop=True)

In [5]:
offertagging.to

     LABEL_ID OFFER_ID
0          54  OFF0007
1         233  OFF0007
2         213  OFF0007
3          56  OFF0007
4          63  OFF0007
5         203  OFF0007
6         216  OFF0007
7         108  OFF0007
8          34  OFF0014
9         123  OFF0014
10        233  OFF0014
11        120  OFF0014
12         17  OFF0014
13        206  OFF0014
14        155  OFF0014
15         21  OFF0014
16        125  OFF0014
17        157  OFF0014
18        134  OFF0005
19         47  OFF0005
20         54  OFF0005
21        144  OFF0005
22        233  OFF0005
23        183  OFF0005
24        227  OFF0005
25        203  OFF0005
26         89  OFF0005
27        103  OFF0022
28        144  OFF0020
29        132  OFF0020
..        ...      ...
301        28  OFF0031
302       230  OFF0031
303        82  OFF0031
304       244  OFF0031
305       118  OFF0031
306       175  OFF0031
307       173  OFF0031
308        43  OFF0037
309        93  OFF0037
310       238  OFF0037
311        39  OFF0037
312        94  OFF0037
313        92  OFF0037
314       217  OFF0037
315       199  OFF0037
316       204  OFF0043
317        74  OFF0043
318       212  OFF0043
319       237  OFF0043
320        89  OFF0043
321       203  OFF0043
322       201  OFF0043
323        43  OFF0039
324        93  OFF0039
325       238  OFF0039
326       139  OFF0039
327       153  OFF0039
328        68  OFF0039
329       242  OFF0039
330       192  OFF0039

[331 rows x 2 columns]

In [5]:
offer = offertagging.OFFER_ID.unique()

In [18]:
for i in offer:
    data = { i : offertagging[offertagging.OFFER_ID == i].LABEL_ID.values.tolist()}
    redis_conn.set(i, json.dumps(data,ensure_ascii=False))
    break

In [20]:
redis_conn.get(offer[0])

'{"OFF0007": [54, 233, 213, 56, 63, 203, 216, 108]}'

In [21]:
redis_conn.flushall()

True

array([ 54, 233, 213,  56,  63, 203, 216, 108])